config/routes.rb
BackChannelApp::Application.routes.draw do
  match 'login' => 'users#login'

  match '/users/admin_page' => 'users#admin_page'

  match '/users/assignOrRevokeAdminRole' => 'users#assignOrRevokeAdminRole'

  match '/users/reports' => 'users#reports'

  match '/users/search' => 'users#search'

  match '/users/logout' => 'users#logout'

=begin
  match '/categories/search' => 'categories#search'

  match '/posts/search' => 'posts#search'

  match '/users/searchUser' => 'users#searchUser'

  match '/posts/searchPost' => 'posts#searchPost'

  match '/categories/searchCategory' => 'categories#searchCategory'
=end

  resources :users

  resources :votes

  resources :comments

  resources :posts do
    resources :tags
  end

  resources :categories

  root :to => 'users#homepage'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :categories
  has_many :posts
  has_many :comments
  has_many :votes

  validates :username, :presence => true
  validates :password, :presence => true
  validates :nickname, :presence => true
 # attr_accessible :nickname, :password, :user_type, :username
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])
    @user.user_type = "user"
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  def homepage

  end

  def login
    username = params[:username]
    password = params[:password]
    @user = User.where("username='#{username}' and password='#{password}'")


    if @user[0]
      session[:user_id] = @user[0].id
      session[:user] = @user[0]
      if @user[0].user_type == "admin"
        redirect_to users_url
      else
        redirect_to posts_url
      end

    else
      redirect_to "/"
      flash[:user_login_err] = "User Authentication Failed"
    end
  end

  def assignOrRevokeAdminRole
    type = params[:type]
    user = User.find(params[:users_id])
    if type == "assign"
      user.user_type="admin"
    else
      user.user_type="user"
    end
    user.save
    redirect_to users_url
  end

  def reports
    @posts = []
    posts = Post.all
    posts.each do |post|
      post_hash = {}
      post_hash['content'] = post.content
      post_hash['no_of_votes'] = Vote.find_all_by_post_id(post.id).length
      post_hash['no_of_comments'] = Comment.find_all_by_post_id(post.id).length
      @posts << post_hash
    end
  end

  def search
      @keyword = params[:keyword]
      @type = params[:type]
      @results = []
      if @type == "user"
           @results = User.where("nickname like '%#{@keyword}%'").map {|result| result.nickname}
      elsif @type == "category"
        @results = Category.where("name like '%#{@keyword}%'").map {|result| result.name}
      else
        @results = Post.where("content like '%#{@keyword}%'").map {|result| result.content}
      end
  end

  def logout
    reset_session
    redirect_to "/"
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <!--<div class="field">
    <%= f.label :user_type %><br />
    <%= f.text_field :user_type %>
  </div> -->
  <div class="field">
    <%= f.label :nickname %><br />
    <%= f.text_field :nickname %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/admin_page.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', root_url %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', root_url %>

app/views/users/homepage.html.erb
<h1><%= flash[:user_login_err] %></h1>

<form action="/login">
<div class="field">
    Username: <input type="text" name="username" />
</div>
<div class="field">
  Password: <input type="password" name="password" />
</div>
  <input type="submit" value="Submit" />
</form>

<a href="<%= new_user_url%>">Register</a>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Password</th>
    <th>User type</th>
    <th>Nickname</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.username %></td>
    <td><%= user.password %></td>
    <td><%= user.user_type %></td>
    <td><%= user.nickname %></td>
    <td><%= link_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% if user.user_type == "admin" %>
    <td><a href=<%="/users/assignOrRevokeAdminRole?users_id=#{user.id}&type=revoke"%>>Revoke Admin Role</a></td>
    <% else%>
        <td><a href=<%="/users/assignOrRevokeAdminRole?users_id=#{user.id}&type=assign"%>>Assign Admin Role</a></td>
    <%end %>
  </tr>
<% end %>
</table>

<br />

<!--<%= link_to 'New User', new_user_path %>-->
<%= link_to 'Show all Categories', categories_url %>
<%= link_to 'Show all Posts', posts_url %>
<a href="/users/reports">Show Reports </a>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/reports.erb
<h1>Reports</h1>

<table border="1">
  <tr>
    <td>Post</td>
    <td>Number of comments</td>
    <td>Number of votes</td>
  </tr>
  <% @posts.each do |post| %>
     <tr>
       <td><%= post['content'] %></td>
       <td><%= post['no_of_votes'] %></td>
       <td><%= post['no_of_comments'] %></td>
     </tr>
  <%end%>

</table>


<%= link_to 'Back', users_url %>

app/views/users/search.html.erb
<h1>Search Results</h1>
Search keyword : <%= @keyword %>
<div>
<br>
<table>
    <% @results.each do |result| %>
        <tr><td><%=result  %></td></tr>
    <% end %>
</table>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @user.username %>
</p>

<p>
  <b>Password:</b>
  <%= @user.password %>
</p>

<!--
<p>
  <b>User type:</b>
  <%= @user.user_type %>
</p>
-->

<p>
  <b>Nickname:</b>
  <%= @user.nickname %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', root_url %>