config/routes.rb
BackChannelApp::Application.routes.draw do
  match 'login' => 'users#login'

  match '/users/admin_page' => 'users#admin_page'

  match '/users/assignOrRevokeAdminRole' => 'users#assignOrRevokeAdminRole'

  match '/users/reports' => 'users#reports'

  match '/users/search' => 'users#search'

  match '/users/logout' => 'users#logout'

=begin
  match '/categories/search' => 'categories#search'

  match '/posts/search' => 'posts#search'

  match '/users/searchUser' => 'users#searchUser'

  match '/posts/searchPost' => 'posts#searchPost'

  match '/categories/searchCategory' => 'categories#searchCategory'
=end

  resources :users

  resources :votes

  resources :comments

  resources :posts do
    resources :tags
  end

  resources :categories

  root :to => 'users#homepage'

end

app/models/post.rb
class Post < ActiveRecord::Base
#  attr_accessible :content
  belongs_to :user
  belongs_to :category
  has_many :comments
  has_many :votes
  has_many :tags

  validates :user, :presence => true
  validates :category, :presence => true
  validates :content, :presence => true
end

app/controllers/posts_controller.rb
  class PostsController < ApplicationController
    # GET /posts
    # GET /posts.json
    def index
      @posts = Post.order("updated_at desc")

      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @posts }
      end
    end

    # GET /posts/1
    # GET /posts/1.json
    def show
      @can_user_vote_for_post = true
      @can_user_vote_for_comment = true
      @post = Post.find(params[:id])
      session[:post] = @post
      @comments = []
      comments = Comment.find_all_by_post_id(params[:id])
      comments.each do |comment|
        comments_hash = {}
        comments_hash['content'] = comment.content
        comments_hash['comment_obj'] = comment
        comments_hash['nickname'] = User.find(comment.user_id).nickname
        comments_hash['user_id'] = comment.user_id
        comments_hash['created_date'] = comment.created_at
        comments_hash['comment_id'] = comment.id
        comments_hash['votes_for_comment'] = Vote.find_all_by_comment_id(comment.id).length
        comments_hash['can_user_vote_for_comment'] = true
        has_user_voted_for_this_comment = Vote.where("user_id=#{session[:user_id]} and comment_id=#{comment.id}").length >0
        comments_hash['has_user_voted_for_this_comment'] = has_user_voted_for_this_comment
        flag = ((session[:user_id] == comment.user_id) || (has_user_voted_for_this_comment))
        if flag
            comments_hash['can_user_vote_for_comment'] = false
        end
        @comments<<comments_hash
      end
        @votes_for_post = Vote.find_all_by_post_id(params[:id]).length
        @has_user_voted_for_this_post = Vote.where("user_id=#{session[:user_id]} and post_id=#{@post.id}").length >0
        flag = ((session[:user_id] == @post.user_id) || (@has_user_voted_for_this_post))
        if flag
            @can_user_vote_for_post = false
        end
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @post }
      end
    end

    # GET /posts/new
    # GET /posts/new.json
    def new
      @post = Post.new
      @categories = get_categories_for_select
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @post }
      end
    end

    # GET /posts/1/edit
    def edit
      @post = Post.find(params[:id])
      @categories = get_categories_for_select
    end

    # POST /posts
    # POST /posts.json
    def create
      @post = Post.new(params[:post])
      @post.user_id=session[:user_id]
      respond_to do |format|
        if @post.save
          format.html { redirect_to @post, notice: 'Post was successfully created.' }
          format.json { render json: @post, status: :created, location: @post }
        else
          format.html { render action: "new" }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    # PUT /posts/1
    # PUT /posts/1.json
    def update
      @post = Post.find(params[:id])

      respond_to do |format|
        if @post.update_attributes(params[:post])
          format.html { redirect_to @post, notice: 'Post was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /posts/1
    # DELETE /posts/1.json
    def destroy
      @post = Post.find(params[:id])
      @post.destroy

      respond_to do |format|
        format.html { redirect_to posts_url }
        format.json { head :no_content }
      end
    end

    def get_categories_for_select
      cats = []
      categories = Category.all
      categories.each {|category| cats<<[category.name, category.id]}
      return cats
    end

    def searchPost

    end
  end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>

    <!--
    <div class="field">
      <%= f.label :userId %><br />
      <%= f.text_field :user_id %>
    </div>
     -->
    <div class="field">
      <%= f.label :Category %><br />
      <%= f.select(:category_id, @categories) %>
    </div>

    <!--<div class="field">
      <%= f.label :category_id %><br />
      <%= f.text_field :category_id %>
    </div> -->

    <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <tr>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.content %></td>
    <td><%= link_to 'Show', post %></td>
    <% if (session[:user].user_type == "admin") || (session[:user_id].eql? post.user_id) %>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @post.content %>
</p>

<div>
  <span style="color:red">Votes</span><br>
   <% display_votes_url =  votes_url << "?type=post&post_id=#{@post.id}"%>
  <%if @has_user_voted_for_this_post%>
        <a href="<%= display_votes_url%>">You and <%= @votes_for_post - 1%> other people voted</a>
  <% else %>
      <a href="<%=display_votes_url%>"><%= @votes_for_post%>  people voted</a>
  <% end %>
  <br>
  <% if @can_user_vote_for_post %>
    <%= link_to 'Vote', new_vote_url<<"?type=post&post_id=#{@post.id}" %>
  <% end %>
</div>
<br>
<span style="color:red">Comments</span>
<br>

<table border="1">
  <% @comments.each do |comment| %>
      <tr>
        <td><%= comment['content'] %></td>
        <td>by <%= comment['nickname'] %></td>
        <% display_votes_url =  votes_url << "?type=comment&comment_id=#{comment['comment_id']}"%>
        <td><% if !comment['has_user_voted_for_this_comment'] %><a href="<%= display_votes_url%>"><%= comment['votes_for_comment'] %> people voted</a><% else %><a href="<%= display_votes_url%>">You and <%= comment['votes_for_comment'] -1 %> other people voted</a><%end%></td>
        <td><% if comment['can_user_vote_for_comment'] %>
            <%= link_to 'Vote', new_vote_url<<"?post_id=#{@post.id}&type=comment&comment_id=#{comment['comment_id']}" %>
          <% end %></td>
        <td><% if session[:user_id] == comment['user_id'] %><a href=<%= edit_comment_url(comment['comment_obj']) %>>Edit Comment</a><% end %></td>
        <td><% if session[:user].user_type == "admin" || session[:user_id] == comment['user_id'] %><a href=<%= "/comments/#{comment['comment_id']}?post_id=#{@post.id}"%> data-confirm="Are you sure?" data-method="delete" rel="nofollow">Delete Comment</a><% end %></td>
        <!--<td><%= comment['created_date'] %></td>-->
      </tr>
      <tr></tr>
  <% end %>
</table>
<br>

<br>
<h2>Add a tag:</h2>
<%= form_for([@post, @post.tags.build]) do |f| %>
    <p>
      <%= f.label :names %><br />
      <%= f.text_area :name %>
    </p>
    <p>
      <%= f.submit %>
    </p>
<% end %>
<%= link_to 'Create Comment', new_comment_url %>

<br >
<br>
<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>